Update build-scan.yml
error output

diff --git a/.github/workflows/build-scan.yml b/.github/workflows/build-scan.yml
--- a/.github/workflows/build-scan.yml
+++ b/.github/workflows/build-scan.yml
@@ -84,3 +84,10 @@ jobs:
           DO_JOB_SUMMARY: true
           DO_PR_COMMENT: true
 
+    - name: Output ScanCentral Log
+      if: failure()
+        run: |
+          echo "=== Begin scancentral.log ==="
+          set SC_CLIENT_VERSION=
+          type "C:\Users\runneradmin\AppData\Local\Fortify\scancentral-24.4.1\log\scancentral.log" || echo "Log file not found."
+          echo "=== End scancentral.log ==="
